export const Questions = [
    {
      prompt: "What is my name?",
      optionA: "Karan",
      optionB: "Ankit",
      optionC: "Saurabh",
      optionD: "Tomar Sahab",
      answer: "A",
    },
    {
      prompt: "Which of this is not a programming language?",
      optionA: "Python",
      optionB: "JavaScript",
      optionC: "MC-03",
      optionD: "Java",
      answer: "C",
    },
    {
      prompt: "Which of this is not a javascript framework?",
      optionA: "React",
      optionB: "Angular",
      optionC: "Vue",
      optionD: "Java",
      answer: "D",
    },
    {
      prompt: "What is the nick name of ankit mittal",
      optionA: "Mittal",
      optionB: "Anks",
      optionC: "BKL",
      optionD: "Mutthal",
      answer: "D",
    },
    {
      prompt: "What is the God of cricket",
      optionA: "Sachin Tendulkar",
      optionB: "Virat Kohli",
      optionC: "Brian Lara",
      optionD: "Ms Dhoni",
      answer: "A",
    },
  ];